from utils.arrays import Array


array = Array()
array.append(0)
array.append(1)
array.append(2)
array.append(3)
array.append(4)
array.append(5)
array.append(6)
array.printf()

print('-------------------------')

array.pop(-2)
array.printf()
array.pop(5)
array.printf()
array.pop(2)
array.printf()
array.pop()
array.printf()
array.pop(0)
array.printf()

print('-------------------------')

array.insert(1, 10)
array.printf()
array.insert(3, 10)
array.printf()
array.insert(-1, 100)
array.printf()
array.insert(-2, 100)
array.printf()
array.insert(-3, 100)
array.printf()
array.insert(-4, 100)
array.printf()
array.insert(-5, 100)
array.printf()
array.insert(-6, 100)
array.printf()

print('-------------------------')

array.replace(0, 111)
array.printf()
array.replace(4, 111)
array.printf()
array.replace(-1, 222)
array.printf()
array.replace(-2, 222)
array.printf()
array.replace(-3, 222)
array.printf()
array.replace(-4, 222)
array.printf()
array.replace(-5, 222)
array.printf()
array.replace(-6, 222)
array.printf()